[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
  '@uni-v2/contracts=lib/v2-periphery/contracts/',
]

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
